<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImageLabPlugin.Plugin\ImageLabPlugin.Plugin.csproj" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
