using Microsoft.Extensions.DependencyInjection;
using ImageLabPlugin.Application.Ports;
using ImageLabPlugin.Application.Watermarking;
using ImageLabPlugin.Application.SpectrumAnalysis;
using ImageLabPlugin.Application.ImageComparison;
using ImageLabPlugin.Domain.Comparison;
using ImageLabPlugin.Domain.Frequency;
using ImageLabPlugin.Domain.Imaging;
using ImageLabPlugin.Infrastructure.Cryptography;
using ImageLabPlugin.Infrastructure.ErrorCorrection;
using ImageLabPlugin.Infrastructure.Imaging;
using ImageLabPlugin.Infrastructure.Persistence;
using ImageLabPlugin.Infrastructure.Ui;
using ImageLabPlugin.Infrastructure.Watermarking;
using ImageLabPlugin.Application.Robustness;
using ImageLabPlugin.Domain.Robustness;
using ImageLabPlugin.Domain.Robustness.Operators;
using ImageLabPlugin.Infrastructure.Robustness;
using ImageLabPlugin.Application.Fingerprinting;
using ImageLabPlugin.Domain.Fingerprinting;
using ImageLabPlugin.Infrastructure.Fingerprinting;
using ImageLabPlugin.Application.BitPlanes;
using ImageLabPlugin.Domain.BitPlanes;
using ImageLabPlugin.Application.LsbSteganography;
using ImageLabPlugin.Domain.Steganography;
using ImageLabPlugin.Infrastructure.Steganography;
using ImageLabPlugin.Application.Convolution;
using ImageLabPlugin.Domain.Convolution;

namespace ImageLabPlugin.Plugin;

public static class ImageLabPluginServices
{
    /// <summary>登记插件自己的业务服务；Standalone 可以复用同一个组合入口。</summary>
    public static IServiceCollection AddImageLabPluginServices(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);
        services.AddSingleton<Dct8x8Transform>();
        services.AddSingleton<LowFrequencyDctTransform>();
        services.AddSingleton<FingerprintLumaNormalizer>();
        services.AddSingleton<FingerprintDistanceCalculator>();
        services.AddSingleton<FingerprintDecisionPolicy>();
        services.AddSingleton<IImageFingerprintAlgorithm, AverageHashAlgorithm>();
        services.AddSingleton<IImageFingerprintAlgorithm, DifferenceHashAlgorithm>();
        services.AddSingleton<IImageFingerprintAlgorithm, PerceptualHashAlgorithm>();
        services.AddSingleton<FrequencySpectrumProjector>();
        services.AddSingleton<ImageChannelConverter>();
        services.AddSingleton<ImageAnalysisProxyProjector>();
        services.AddSingleton<ImagePairValidator>();
        services.AddSingleton<FullReferenceQualityAnalyzer>();
        services.AddSingleton<ImageHistogramAnalyzer>();
        services.AddSingleton<ImageDifferenceProxyAnalyzer>();
        services.AddSingleton<ImageDifferenceProxyProjector>();
        services.AddSingleton<DifferenceHeatmapProjector>();
        services.AddSingleton<ImagePairPixelInspector>();
        services.AddSingleton<Fft1DTransform>();
        services.AddSingleton<Fft2DTransform>();
        services.AddSingleton<SpectrumProjector>();
        services.AddSingleton<DctSpectrumProjector>();
        services.AddSingleton<DctBlockAnalyzer>();
        services.AddSingleton<RadialEnergyAnalyzer>();
        services.AddSingleton<FrequencyBandMaskFactory>();
        services.AddSingleton<ReedSolomonCodec>();
        services.AddSingleton<IRandomSource, CryptographicRandomSource>();
        services.AddSingleton<IImageCodec, AvaloniaImageCodec>();
        services.AddSingleton<IAtomicFileWriter, AtomicFileWriter>();
        services.AddSingleton<AvaloniaImageLabFileDialog>();
        services.AddSingleton<IImageFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<IPayloadFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<IComparisonReportFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<IRobustnessReportFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<IFingerprintReportFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<ILsbReportFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<ILsbPayloadFileReader, LsbPayloadFileReader>();
        services.AddSingleton<ITextClipboard>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<ImageComparisonSummarySerializer>();
        services.AddSingleton<WatermarkFrameProtocol>();
        services.AddSingleton<FrequencyWatermarkCarrier>();
        services.AddSingleton<IEstimateWatermarkCapacityUseCase, EstimateWatermarkCapacityUseCase>();
        services.AddSingleton<IInspectWatermarkUseCase, InspectWatermarkUseCase>();
        services.AddSingleton<IExtractWatermarkUseCase, ExtractWatermarkUseCase>();
        services.AddSingleton<IEmbedWatermarkUseCase, EmbedWatermarkUseCase>();
        services.AddSingleton<IAnalyzeSpectrumUseCase, AnalyzeSpectrumUseCase>();
        services.AddSingleton<IInspectDctBlockUseCase, InspectDctBlockUseCase>();
        services.AddSingleton<IReconstructSpectrumBandUseCase, ReconstructSpectrumBandUseCase>();
        services.AddSingleton<IProjectSpectrumUseCase, ProjectSpectrumUseCase>();
        services.AddSingleton<IPrepareImageComparisonUseCase, PrepareImageComparisonUseCase>();
        services.AddSingleton<IProjectImageDifferenceUseCase, ProjectImageDifferenceUseCase>();
        services.AddSingleton<IInspectImagePairUseCase, InspectImagePairUseCase>();
        services.AddSingleton<IExportComparisonSummaryUseCase, ExportComparisonSummaryUseCase>();
        services.AddSingleton<RobustnessRecipeValidator>();
        services.AddSingleton<RobustnessExperimentPlanner>();
        services.AddSingleton<IImagePerturbationOperator, DeterministicPixelOperator>();
        services.AddSingleton<IImagePerturbationOperator, GaussianNoiseOperator>();
        services.AddSingleton<IImagePerturbationOperator, SaltPepperNoiseOperator>();
        services.AddSingleton<IImagePerturbationOperator, BrightnessOperator>();
        services.AddSingleton<IImagePerturbationOperator, ContrastOperator>();
        services.AddSingleton<IImagePerturbationOperator, GammaOperator>();
        services.AddSingleton<IImagePerturbationOperator, SaturationOperator>();
        services.AddSingleton<IImagePerturbationOperator, ColorBiasOperator>();
        services.AddSingleton<IImagePerturbationOperator, GaussianBlurOperator>();
        services.AddSingleton<IImagePerturbationOperator, MedianBlurOperator>();
        services.AddSingleton<IImagePerturbationOperator, UnsharpMaskOperator>();
        services.AddSingleton<IImagePerturbationOperator, ScaleOperator>();
        services.AddSingleton<IImagePerturbationOperator, CropOperator>();
        services.AddSingleton<IImagePerturbationOperator, PadOperator>();
        services.AddSingleton<IImagePerturbationOperator, TranslateOperator>();
        services.AddSingleton<IImagePerturbationOperator, RotateOperator>();
        services.AddSingleton<IImagePerturbationOperator, PerspectiveOperator>();
        services.AddSingleton<IImagePerturbationOperator, JpegReencodeOperator>();
        services.AddSingleton<PerturbationChainExecutor>();
        services.AddSingleton<IWatermarkDiagnosticReader, WatermarkDiagnosticReader>();
        services.AddSingleton<RobustnessReportSerializer>();
        services.AddSingleton<IPrepareRobustnessBaselineUseCase, PrepareRobustnessBaselineUseCase>();
        services.AddSingleton<IPlanRobustnessExperimentUseCase, PlanRobustnessExperimentUseCase>();
        services.AddSingleton<IRunRobustnessExperimentUseCase, RunRobustnessExperimentUseCase>();
        services.AddSingleton<IExportRobustnessReportUseCase, RobustnessReportExportUseCase>();
        services.AddSingleton<FingerprintReportSerializer>();
        services.AddSingleton<IPrepareFingerprintComparisonUseCase, PrepareFingerprintComparisonUseCase>();
        services.AddSingleton<IFingerprintStabilityChannel, FingerprintStabilityChannel>();
        services.AddSingleton<IRunFingerprintStabilityUseCase, RunFingerprintStabilityUseCase>();
        services.AddSingleton<IExportFingerprintReportUseCase, FingerprintReportExportUseCase>();
        services.AddSingleton<IFingerprintObservationProbe, FingerprintObservationProbe>();
        services.AddSingleton<BitPlaneChannelExtractor>();
        services.AddSingleton<BitPlaneStatisticsAnalyzer>();
        services.AddSingleton<BitPlaneProjector>();
        services.AddSingleton<BitPlaneReconstructor>();
        services.AddSingleton<BitPlanePixelInspector>();
        services.AddSingleton<IPrepareBitPlaneSessionUseCase, PrepareBitPlaneSessionUseCase>();
        services.AddSingleton<IAnalyzeBitPlaneChannelUseCase, AnalyzeBitPlaneChannelUseCase>();
        services.AddSingleton<IProjectBitPlaneViewUseCase, ProjectBitPlaneViewUseCase>();
        services.AddSingleton<IExportBitPlaneImageUseCase, ExportBitPlaneImageUseCase>();
        services.AddSingleton<LsbFrameCodec>();
        services.AddSingleton<LsbCapacityCalculator>();
        services.AddSingleton<ILsbSlotOrder, SequentialLsbSlotOrder>();
        services.AddSingleton<ILsbSlotOrder, PseudoRandomLsbSlotOrder>();
        services.AddSingleton<LsbEmbeddingEngine>();
        services.AddSingleton<LsbExtractionEngine>();
        services.AddSingleton<LsbStatisticsAnalyzer>();
        services.AddSingleton<LsbPreviewProjector>();
        services.AddSingleton<LsbPixelInspector>();
        services.AddSingleton<LsbExperimentReportSerializer>();
        services.AddSingleton<IPrepareLsbExperimentUseCase, PrepareLsbExperimentUseCase>();
        services.AddSingleton<IEstimateLsbCapacityUseCase, EstimateLsbCapacityUseCase>();
        services.AddSingleton<IEmbedAndAnalyzeLsbUseCase, EmbedAndAnalyzeLsbUseCase>();
        services.AddSingleton<IExtractLsbPayloadUseCase, ExtractLsbPayloadUseCase>();
        services.AddSingleton<IRunLsbFragilityUseCase, RunLsbFragilityUseCase>();
        services.AddSingleton<IExportLsbImageUseCase, ExportLsbImageUseCase>();
        services.AddSingleton<IExportLsbReportUseCase, ExportLsbReportUseCase>();
        services.AddSingleton<ILoadLsbPayloadUseCase, LoadLsbPayloadUseCase>();
        services.AddSingleton<IInspectLsbPixelUseCase, InspectLsbPixelUseCase>();
        // 卷积领域类均为无状态数学服务；Document/Session 才拥有每实例图片、结果和取消状态。
        services.AddSingleton<ConvolutionKernelParser>();
        services.AddSingleton<ConvolutionPresetFactory>();
        services.AddSingleton<SpatialConvolver>();
        services.AddSingleton<GradientCombiner>();
        services.AddSingleton<ConvolutionImageProcessor>();
        services.AddSingleton<KernelFrequencyResponseAnalyzer>();
        services.AddSingleton<ConvolutionDifferenceProjector>();
        services.AddSingleton<ConvolutionPixelInspector>();
        services.AddSingleton<IPrepareConvolutionSessionUseCase, PrepareConvolutionSessionUseCase>();
        services.AddSingleton<IRenderConvolutionPreviewUseCase, RenderConvolutionPreviewUseCase>();
        services.AddSingleton<IInspectConvolutionPixelUseCase, InspectConvolutionPixelUseCase>();
        services.AddSingleton<IRenderKernelResponseUseCase, RenderKernelResponseUseCase>();
        services.AddSingleton<IRenderFullConvolutionUseCase, RenderFullConvolutionUseCase>();
        services.AddSingleton<IExportConvolutionImageUseCase, ExportConvolutionImageUseCase>();
        return services;
    }
}
