using Microsoft.Extensions.DependencyInjection;
using ImageLabPlugin.Application.Ports;
using ImageLabPlugin.Application.Watermarking;
using ImageLabPlugin.Application.SpectrumAnalysis;
using ImageLabPlugin.Application.ImageComparison;
using ImageLabPlugin.Domain.Comparison;
using ImageLabPlugin.Domain.Frequency;
using ImageLabPlugin.Domain.Imaging;
using ImageLabPlugin.Infrastructure.Cryptography;
using ImageLabPlugin.Infrastructure.ErrorCorrection;
using ImageLabPlugin.Infrastructure.Imaging;
using ImageLabPlugin.Infrastructure.Persistence;
using ImageLabPlugin.Infrastructure.Ui;
using ImageLabPlugin.Infrastructure.Watermarking;
using ImageLabPlugin.Application.Robustness;
using ImageLabPlugin.Domain.Robustness;
using ImageLabPlugin.Domain.Robustness.Operators;
using ImageLabPlugin.Infrastructure.Robustness;

namespace ImageLabPlugin.Plugin;

public static class ImageLabPluginServices
{
    /// <summary>登记插件自己的业务服务；Standalone 可以复用同一个组合入口。</summary>
    public static IServiceCollection AddImageLabPluginServices(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);
        services.AddSingleton<Dct8x8Transform>();
        services.AddSingleton<FrequencySpectrumProjector>();
        services.AddSingleton<ImageChannelConverter>();
        services.AddSingleton<ImageAnalysisProxyProjector>();
        services.AddSingleton<ImagePairValidator>();
        services.AddSingleton<FullReferenceQualityAnalyzer>();
        services.AddSingleton<ImageHistogramAnalyzer>();
        services.AddSingleton<ImageDifferenceProxyAnalyzer>();
        services.AddSingleton<ImageDifferenceProxyProjector>();
        services.AddSingleton<DifferenceHeatmapProjector>();
        services.AddSingleton<ImagePairPixelInspector>();
        services.AddSingleton<Fft1DTransform>();
        services.AddSingleton<Fft2DTransform>();
        services.AddSingleton<SpectrumProjector>();
        services.AddSingleton<DctSpectrumProjector>();
        services.AddSingleton<DctBlockAnalyzer>();
        services.AddSingleton<RadialEnergyAnalyzer>();
        services.AddSingleton<FrequencyBandMaskFactory>();
        services.AddSingleton<ReedSolomonCodec>();
        services.AddSingleton<IRandomSource, CryptographicRandomSource>();
        services.AddSingleton<IImageCodec, AvaloniaImageCodec>();
        services.AddSingleton<IAtomicFileWriter, AtomicFileWriter>();
        services.AddSingleton<AvaloniaImageLabFileDialog>();
        services.AddSingleton<IImageFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<IPayloadFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<IComparisonReportFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<IRobustnessReportFileDialog>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<ITextClipboard>(static provider => provider.GetRequiredService<AvaloniaImageLabFileDialog>());
        services.AddSingleton<ImageComparisonSummarySerializer>();
        services.AddSingleton<WatermarkFrameProtocol>();
        services.AddSingleton<FrequencyWatermarkCarrier>();
        services.AddSingleton<IEstimateWatermarkCapacityUseCase, EstimateWatermarkCapacityUseCase>();
        services.AddSingleton<IInspectWatermarkUseCase, InspectWatermarkUseCase>();
        services.AddSingleton<IExtractWatermarkUseCase, ExtractWatermarkUseCase>();
        services.AddSingleton<IEmbedWatermarkUseCase, EmbedWatermarkUseCase>();
        services.AddSingleton<IAnalyzeSpectrumUseCase, AnalyzeSpectrumUseCase>();
        services.AddSingleton<IInspectDctBlockUseCase, InspectDctBlockUseCase>();
        services.AddSingleton<IReconstructSpectrumBandUseCase, ReconstructSpectrumBandUseCase>();
        services.AddSingleton<IProjectSpectrumUseCase, ProjectSpectrumUseCase>();
        services.AddSingleton<IPrepareImageComparisonUseCase, PrepareImageComparisonUseCase>();
        services.AddSingleton<IProjectImageDifferenceUseCase, ProjectImageDifferenceUseCase>();
        services.AddSingleton<IInspectImagePairUseCase, InspectImagePairUseCase>();
        services.AddSingleton<IExportComparisonSummaryUseCase, ExportComparisonSummaryUseCase>();
        services.AddSingleton<RobustnessRecipeValidator>();
        services.AddSingleton<RobustnessExperimentPlanner>();
        services.AddSingleton<IImagePerturbationOperator, DeterministicPixelOperator>();
        services.AddSingleton<IImagePerturbationOperator, GaussianNoiseOperator>();
        services.AddSingleton<IImagePerturbationOperator, SaltPepperNoiseOperator>();
        services.AddSingleton<IImagePerturbationOperator, BrightnessOperator>();
        services.AddSingleton<IImagePerturbationOperator, ContrastOperator>();
        services.AddSingleton<IImagePerturbationOperator, GammaOperator>();
        services.AddSingleton<IImagePerturbationOperator, SaturationOperator>();
        services.AddSingleton<IImagePerturbationOperator, ColorBiasOperator>();
        services.AddSingleton<IImagePerturbationOperator, GaussianBlurOperator>();
        services.AddSingleton<IImagePerturbationOperator, MedianBlurOperator>();
        services.AddSingleton<IImagePerturbationOperator, UnsharpMaskOperator>();
        services.AddSingleton<IImagePerturbationOperator, ScaleOperator>();
        services.AddSingleton<IImagePerturbationOperator, CropOperator>();
        services.AddSingleton<IImagePerturbationOperator, PadOperator>();
        services.AddSingleton<IImagePerturbationOperator, TranslateOperator>();
        services.AddSingleton<IImagePerturbationOperator, RotateOperator>();
        services.AddSingleton<IImagePerturbationOperator, PerspectiveOperator>();
        services.AddSingleton<IImagePerturbationOperator, JpegReencodeOperator>();
        services.AddSingleton<PerturbationChainExecutor>();
        services.AddSingleton<IWatermarkDiagnosticReader, WatermarkDiagnosticReader>();
        services.AddSingleton<RobustnessReportSerializer>();
        services.AddSingleton<IPrepareRobustnessBaselineUseCase, PrepareRobustnessBaselineUseCase>();
        services.AddSingleton<IPlanRobustnessExperimentUseCase, PlanRobustnessExperimentUseCase>();
        services.AddSingleton<IRunRobustnessExperimentUseCase, RunRobustnessExperimentUseCase>();
        services.AddSingleton<IExportRobustnessReportUseCase, RobustnessReportExportUseCase>();
        return services;
    }
}
